### ISSUE TITLE
`DENO_DIR` not set under Fish

### ISSUE THREAD

**Issue by brandonpittman** [ivebencrazy/johnny_decimal#10]
Not sure if the user is expected to set this env var, but running commands that fall down to the `$DENO_DIR` line fail because the variable isn't set by the script.

I added `set DENO_DIR $HOME/.deno` and it worked just fine.

**Comment by bpevs** [comment]
Hmmm `$DENO_DIR` was added during setup in the past.  Let me ask around and see if that changed.  Or maybe it's just setup internally to Deno...  In any case, yeah, if it is not automatic, then I'll need to add that to the setup script at least.

**Comment by brandonpittman** [comment]
Something about not having the ID convention exactly right caused a fall-through in the script and then the `DENO_DIR` error occurred. After renaming my IDs, this error also stopped.

**Comment by brandonpittman** [comment]
Reopening. This is still happening.

**Comment by bpevs** [comment]
Should be fixed in v1.1.1 (https://github.com/bpevs/johnny_decimal/commit/46d011ea5ddd27055b0682c5d471e304e0b559b9)

According to [https://deno.land/manual@v1.29.1/getting_started/setup_your_environment#environment-variables](Deno Docs), actually the correct variable to be checking looks to be `DENO_INSTALL_ROOT`, defaulting to `$HOME/.deno/bin`. So there's just one new check in the sh/fish scripts.

Change doesn't affect users that already used `jd install`.
